-- E-névjegy production schema for Supabase/Postgres
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid unique references auth.users(id) on delete cascade,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  display_name text not null check (char_length(display_name) between 2 and 80),
  job_title text not null default '' check (char_length(job_title) <= 100),
  company text not null default '' check (char_length(company) <= 100),
  bio text not null default '' check (char_length(bio) <= 420),
  public_email text not null default '' check (char_length(public_email) <= 254),
  phone text not null default '' check (char_length(phone) <= 40),
  website text not null default '' check (char_length(website) <= 300),
  address text not null default '' check (char_length(address) <= 180),
  avatar_url text,
  theme text not null default 'midnight' check (theme in ('midnight', 'ivory', 'forest', 'plum')),
  accent_color text not null default '#55d6be' check (accent_color ~ '^#[0-9A-Fa-f]{6}$'),
  is_public boolean not null default true,
  views_count bigint not null default 0,
  saves_count bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.social_links (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  platform text not null check (platform in ('linkedin', 'facebook', 'instagram', 'youtube', 'tiktok', 'x', 'github', 'custom')),
  label text not null check (char_length(label) between 1 and 40),
  url text not null check (url ~ '^https?://'),
  sort_order integer not null default 0 check (sort_order between 0 and 20),
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.profile_events (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null check (event_type in ('view', 'save', 'phone', 'email', 'website', 'social', 'share')),
  link_key text not null default '' check (char_length(link_key) <= 100),
  referrer text check (char_length(referrer) <= 500),
  user_agent text check (char_length(user_agent) <= 500),
  occurred_at timestamptz not null default now()
);

create table if not exists public.privacy_consents (
  user_id uuid primary key references auth.users(id) on delete cascade,
  privacy_version text not null,
  accepted_at timestamptz not null default now()
);

create index if not exists profiles_public_slug_idx on public.profiles(slug) where is_public = true;
create index if not exists social_links_profile_sort_idx on public.social_links(profile_id, sort_order);
create index if not exists profile_events_profile_time_idx on public.profile_events(profile_id, occurred_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create or replace function public.increment_profile_counters()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.event_type = 'view' then
    update public.profiles set views_count = views_count + 1 where id = new.profile_id;
  elsif new.event_type = 'save' then
    update public.profiles set saves_count = saves_count + 1 where id = new.profile_id;
  end if;
  return new;
end;
$$;

drop trigger if exists profile_events_increment_counter on public.profile_events;
create trigger profile_events_increment_counter
after insert on public.profile_events
for each row execute function public.increment_profile_counters();

create or replace function public.record_signup_consent()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  consent_version text;
begin
  consent_version := coalesce(new.raw_user_meta_data ->> 'privacy_version', 'unknown');
  insert into public.privacy_consents(user_id, privacy_version)
  values (new.id, consent_version)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists auth_user_signup_consent on auth.users;
create trigger auth_user_signup_consent
after insert on auth.users
for each row execute function public.record_signup_consent();

alter table public.profiles enable row level security;
alter table public.social_links enable row level security;
alter table public.profile_events enable row level security;
alter table public.privacy_consents enable row level security;

drop policy if exists "profiles_public_or_owner_read" on public.profiles;
create policy "profiles_public_or_owner_read" on public.profiles
for select using (is_public = true or owner_id = auth.uid());

drop policy if exists "profiles_owner_insert" on public.profiles;
create policy "profiles_owner_insert" on public.profiles
for insert to authenticated with check (owner_id = auth.uid());

drop policy if exists "profiles_owner_update" on public.profiles;
create policy "profiles_owner_update" on public.profiles
for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());

drop policy if exists "profiles_owner_delete" on public.profiles;
create policy "profiles_owner_delete" on public.profiles
for delete to authenticated using (owner_id = auth.uid());

drop policy if exists "social_links_public_or_owner_read" on public.social_links;
create policy "social_links_public_or_owner_read" on public.social_links
for select using (
  exists (
    select 1 from public.profiles
    where profiles.id = social_links.profile_id
      and (profiles.is_public = true or profiles.owner_id = auth.uid())
  )
);

drop policy if exists "social_links_owner_insert" on public.social_links;
create policy "social_links_owner_insert" on public.social_links
for insert to authenticated with check (
  exists (select 1 from public.profiles where profiles.id = social_links.profile_id and profiles.owner_id = auth.uid())
);

drop policy if exists "social_links_owner_update" on public.social_links;
create policy "social_links_owner_update" on public.social_links
for update to authenticated using (
  exists (select 1 from public.profiles where profiles.id = social_links.profile_id and profiles.owner_id = auth.uid())
) with check (
  exists (select 1 from public.profiles where profiles.id = social_links.profile_id and profiles.owner_id = auth.uid())
);

drop policy if exists "social_links_owner_delete" on public.social_links;
create policy "social_links_owner_delete" on public.social_links
for delete to authenticated using (
  exists (select 1 from public.profiles where profiles.id = social_links.profile_id and profiles.owner_id = auth.uid())
);

drop policy if exists "events_public_profile_insert" on public.profile_events;
create policy "events_public_profile_insert" on public.profile_events
for insert to anon, authenticated with check (
  exists (select 1 from public.profiles where profiles.id = profile_events.profile_id and profiles.is_public = true)
);

drop policy if exists "events_owner_read" on public.profile_events;
create policy "events_owner_read" on public.profile_events
for select to authenticated using (
  exists (select 1 from public.profiles where profiles.id = profile_events.profile_id and profiles.owner_id = auth.uid())
);

drop policy if exists "consents_owner_read" on public.privacy_consents;
create policy "consents_owner_read" on public.privacy_consents
for select to authenticated using (user_id = auth.uid());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 3145728, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "avatars_public_read" on storage.objects;
create policy "avatars_public_read" on storage.objects
for select using (bucket_id = 'avatars');

drop policy if exists "avatars_owner_insert" on storage.objects;
create policy "avatars_owner_insert" on storage.objects
for insert to authenticated with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "avatars_owner_update" on storage.objects;
create policy "avatars_owner_update" on storage.objects
for update to authenticated using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "avatars_owner_delete" on storage.objects;
create policy "avatars_owner_delete" on storage.objects
for delete to authenticated using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

-- Public demo profile shown on a fresh deployment.
insert into public.profiles (
  id, owner_id, slug, display_name, job_title, company, bio, public_email,
  phone, website, address, theme, accent_color, is_public, views_count, saves_count
)
values (
  '00000000-0000-4000-8000-000000000001', null, 'rajmund', 'Csukárdi Rajmund',
  'Fejlesztő · tanácsadó', 'RayWorks | IT Solutions',
  'Emberközpontú digitális megoldásokat készítek vállalkozásoknak – az ötlettől a működő rendszerig.',
  'info@rayworks.hu', '+36 70 298 0003', 'https://rayworks.hu', 'Budapest, Magyarország',
  'midnight', '#55d6be', true, 1284, 317
)
on conflict (id) do nothing;

insert into public.social_links (profile_id, platform, label, url, sort_order, enabled)
select '00000000-0000-4000-8000-000000000001', values_table.platform, values_table.label, values_table.url, values_table.sort_order, true
from (values
  ('linkedin', 'LinkedIn', 'https://www.linkedin.com', 0),
  ('facebook', 'Facebook', 'https://www.facebook.com', 1)
) as values_table(platform, label, url, sort_order)
where not exists (
  select 1 from public.social_links where profile_id = '00000000-0000-4000-8000-000000000001'
);
